// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "34",
    name: "Imed Benali",
    email: "imed.benali@outlook.fr",
    photo: "/pfp.jpg",
    phone: "24 305 678",
    departmentId: "1",
  },
  {
    id: 2,
    teacherId: "12",
    name: "Fatma Alami",
    email: "fatma.alami@hotmail.com",
    photo: "/pfp.jpg",
    phone: "25 456 780",
    departmentId: "2",
  },
  {
    id: 3,
    teacherId: "78",
    name: "Mohammed Zaid",
    email: "mohammed.zaid@gmail.com",
    photo: "/pfp.jpg",
    phone: "54 345 665",
    departmentId: "3",
  },
  {
    id: 4,
    teacherId: "56",
    name: "Khaled Jebali",
    email: "khaled.jebali@yahoo.fr",
    photo: "/pfp.jpg",
    phone: "23 456 781",
    departmentId: "1",
  },
  {
    id: 5,
    teacherId: "98",
    name: "Amina Bouazizi",
    email: "amina.bouazizi@gmail.com",
    photo: "/pfp.jpg",
    phone: "22 568 901",
    departmentId: "2",
  },
  {
    id: 6,
    teacherId: "43",
    name: "Omar Harb",
    email: "omar.harb@hotmail.com",
    photo: "/pfp.jpg",
    phone: "23 204 678",
    departmentId: "3",
  },
  {
    id: 7,
    teacherId: "67",
    name: "Leila Fathi",
    email: "leila.fathi@outlook.fr",
    photo: "/pfp.jpg",
    phone: "22 078 903",
    departmentId: "1",
  },
  {
    id: 8,
    teacherId: "11",
    name: "Youssef Laarbi",
    email: "youssef.laarbi@gmail.com",
    photo: "/pfp.jpg",
    phone: "94 234 009",
    departmentId: "2",
  },
  {
    id: 9,
    teacherId: "101",
    name: "Samiha Mhenni",
    email: "samiha.mhenni@yahoo.fr",
    photo: "/pfp.jpg",
    phone: "93 230 558",
    departmentId: "3",
  },
  {
    id: 10,
    teacherId: "59",
    name: "Ali Boughanem",
    email: "ali.boughanem@hotmail.com",
    photo: "/pfp.jpg",
    phone: "24 235 009",
    departmentId: "1",
  },
  {
    id: 11,
    teacherId: "35",
    name: "Anis Benali",
    email: "anis.benali@gmail.fr",
    photo: "/pfp.jpg",
    phone: "24 333 678",
    departmentId: "1",
  },
];


export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    exam_id: 1,
    subject: "Analyse 3",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 3,
    subject: "Développement d'applications Mobiles",
    department_id: 3,
    exam_date: "2025-02-17",
    start_time: "-",
    end_time: "-",
    coefficient: 1.25,
    duration: "2h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 4,
    subject: "Programmation Temps Réel et Concurrente",
    department_id: 2,
    exam_date: "2025-02-18",
    start_time: "-",
    end_time: "-",
    coefficient: 2,
    duration: "1h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 5,
    subject: "Ingénierie des protocoles de communication",
    department_id: 3,
    exam_date: "2025-02-19",
    start_time: "-",
    end_time: "-",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 6,
    subject: "Linux pour l’embarqué",
    department_id: 3,
    exam_date: "2025-02-20",
    start_time: "-",
    end_time: "-",
    coefficient: 1,
    duration: "1h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 7,
    subject: "Systèmes Temps Réel",
    department_id: 1,
    exam_date: "2025-02-21",
    start_time: "-",
    end_time: "-",
    coefficient: 2,
    duration: "2h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 8,
    subject: "Technologie et conception des Circuits Intégrés Numériques",
    department_id: 2,
    exam_date: "2025-02-22",
    start_time: "-",
    end_time: "-",
    coefficient: 1.25,
    duration: "0.5h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 9,
    subject: "Systèmes d'exploitation embarqués temps réel (EmRTOS)",
    department_id: 2,
    exam_date: "2025-02-23",
    start_time: "-",
    end_time: "-",
    coefficient: 2,
    duration: "1h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 10,
    subject: "Optimisation et méthodes numériques",
    department_id: 2,
    exam_date: "2025-02-24",
    start_time: "-",
    end_time: "-",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  {
    exam_id: 11,
    subject: "Français",
    department_id: 2,
    exam_date: "2025-02-24",
    start_time: "-",
    end_time: "-",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "-",
    surveillant1id: 34,
    surveillant2id: 12,
  },
  
];

export const subjectsDataTest = [
  {
    exam_id: 1,
    subject: "Analyse 3",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
  {
    exam_id: 2,
    subject: "Processus stochastique",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "10:30",
    end_time: "12:00",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
  },
];

export const directeurData = [
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 2,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 3,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 2,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
];

export const chefData = [
  {
    exam_id: 7,
    subject: "Programmation C++",
    department_id: 1,
    exam_date: "2025-02-15",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "A31",
    surveillant: "Sami Hammami",
  },
  {
    exam_id: 8,
    subject: "Programmation Mobile",
    department_id: 1,
    exam_date: "2025-02-16",
    start_time: "9:00",
    end_time: "10:30",
    coefficient: 2,
    duration: "1.5h",
    salle: "B12",
    surveillant: "Samir Alrfawi",

  },
  {
    exam_id: 9,
    subject: "Python",
    department_id: 1,
    exam_date: "2025-02-17",
    start_time: "10:00",
    end_time: "11:30",
    coefficient: 1.8,
    duration: "1.5h",
    salle: "C22",
    surveillant: "-",
  },
  {
    exam_id: 10,
    subject: "Programmation Web Avancée",
    department_id: 1,
    exam_date: "2025-02-18",
    start_time: "8:00",
    end_time: "9:30",
    coefficient: 2.2,
    duration: "1.5h",
    salle: "B11",
    surveillant: "-",
  },
  {
    exam_id: 11,
    subject: "Compilation",
    department_id: 1,
    exam_date: "2025-02-19",
    start_time: "9:30",
    end_time: "11:00",
    coefficient: 1.7,
    duration: "1.5h",
    salle: "A13",
    surveillant: "-",
  },
  {
    exam_id: 12,
    subject: "Sécurité informatique",
    department_id: 1,
    exam_date: "2025-02-20",
    start_time: "8:00",
    end_time: "9:30",
    coefficient: 2,
    duration: "1.5h",
    salle: "B22",
    surveillant: "Adel Chabi",
  },
  {
    exam_id: 13,
    subject: "Modélisation UML/OCL",
    department_id: 1,
    exam_date: "2025-02-21",
    start_time: "10:00",
    end_time: "11:30",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "C11",
    surveillant: "-",
  },
  {
    exam_id: 14,
    subject: "Systémes d'exploitation",
    department_id: 1,
    exam_date: "2025-02-22",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.6,
    duration: "1.5h",
    salle: "A21",
    surveillant: "-",
  },
  {
    exam_id: 15,
    subject: "Applications logicielles d'entreprise",
    department_id: 1,
    exam_date: "2025-02-23",
    start_time: "9:00",
    end_time: "10:30",
    coefficient: 2,
    duration: "1.5h",
    salle: "B14",
    surveillant: "-",
  },
  {
    exam_id: 16,
    subject: "Base de données 1",
    department_id: 1,
    exam_date: "2025-02-24",
    start_time: "10:00",
    end_time: "11:30",
    coefficient: 1.9,
    duration: "1.5h",
    salle: "A12",
    surveillant: "Mohamed Ben Salem",
  },
  {
    exam_id: 17,
    subject: "Machine Learning",
    department_id: 1,
    exam_date: "2025-02-25",
    start_time: "8:00",
    end_time: "9:30",
    coefficient: 2.5,
    duration: "1.5h",
    salle: "A33",
    surveillant: "-",
  },
  {
    exam_id: 18,
    subject: "Atelier C",
    department_id: 1,
    exam_date: "2025-02-26",
    start_time: "9:00",
    end_time: "10:30",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "C21",
    surveillant: "-",
  },
  {
    exam_id: 19,
    subject: "Graphes et Optimisation",
    department_id: 1,
    exam_date: "2025-02-27",
    start_time: "8:00",
    end_time: "9:30",
    coefficient: 1.8,
    duration: "1.5h",
    salle: "A15",
    surveillant: "-",
  },
  {
    exam_id: 20,
    subject: "Algorithmique et Structures de Données",
    department_id: 1,
    exam_date: "2025-02-28",
    start_time: "10:00",
    end_time: "11:30",
    coefficient: 2,
    duration: "1.5h",
    salle: "B21",
    surveillant: "Slimene Hammemi",
  },
  {
    exam_id: 21,
    subject: "Virtualisation et Cloud",
    department_id: 1,
    exam_date: "2025-03-01",
    start_time: "8:30",
    end_time: "10:00",
    coefficient: 1.5,
    duration: "1.5h",
    salle: "B32",
    surveillant: "-",
  },
  {
    exam_id: 22,
    subject: "Programmation Java",
    department_id: 1,
    exam_date: "2025-03-02",
    start_time: "9:00",
    end_time: "10:30",
    coefficient: 2.1,
    duration: "1.5h",
    salle: "C15",
    surveillant: "-",
  },
  {
    exam_id: 23,
    subject: "Optimisation Combinatoire",
    department_id: 1,
    exam_date: "2025-03-03",
    start_time: "8:00",
    end_time: "9:30",
    coefficient: 1.7,
    duration: "1.5h",
    salle: "C12",
    surveillant: "-",
  }
];



export const classesData = [
  {
    id: 1,
    name: "A21",
    location: "Etage 2",
    capacity: 31,
    disponibility: "Available",
  },
  {
    id: 2,
    name: "A22",
    location: "Etage 2",
    capacity: 29,
    disponibility: "Available",
  },
  {
    id: 3,
    name: "Amphi Kanoun",
    location: "Ground Floor",
    capacity: 59,
    disponibility: "Available",
  },
  {
    id: 4,
    name: "Amphi B",
    location: "Ground Floor",
    capacity: 60,
    disponibility: "Available",
  },
  {
    id: 5,
    name: "A31",
    location: "Etage 3",
    capacity: 32,
    disponibility: "Available",
  },
  {
    id: 6,
    name: "B21",
    location: "Etage 2",
    capacity: 30,
    disponibility: "Available",
  },
  {
    id: 7,
    name: "B22",
    location: "Etage 2",
    capacity: 28,
    disponibility: "Available",
  },
  {
    id: 8,
    name: "C31",
    location: "Etage 3",
    capacity: 31,
    disponibility: "Available",
  },
  {
    id: 9,
    name: "C32",
    location: "Etage 3",
    capacity: 29,
    disponibility: "Unavailable",
  },
  {
    id: 10,
    name: "C33",
    location: "Etage 3",
    capacity: 33,
    disponibility: "Available",
  },
  {
    id: 11,
    name: "C35",
    location: "Etage 3",
    capacity: 30,
    disponibility: "Unavailable",
  },
];



export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];